name: manga311
channels:
  - rapidsai 
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.11.*
  - ipykernel
  - tqdm
  - rich
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - cudnn
  - pytorch::pytorch>=2.1.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchaudio
  - pytorch::torchvision
  - torchmetrics
  - torchinfo
  - rapids=24.04
  - cuda-version=11.8
  - transformers
  - datasets
  - pytorch::faiss-gpu>=1.8.0
  - conda-forge::timm
  - conda-forge::shapely
  - ipywidgets
  - jupyter
  - einops
  - typing-extensions
  - networkx
  - pip:
      - tensordict
